services:
  report-server:
    build:
      context: .
      target: report-server
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/dev/null}:/gcp/creds.json:ro
    environment:
      PORT: "8000"
      GOOGLE_APPLICATION_CREDENTIALS: /gcp/creds.json
    restart: unless-stopped

  run-tests:
    build:
      context: .
      target: test
    env_file: .env
    profiles: ["test"]
